version: '3'
services:
  proxy:
    build: ./proxy
    command: nodemon app.js
    volumes:
      - ./proxy:/app
      - ./common:/common
    working_dir: /app
    ports:
      - 8080:8080
    environment:
      - NODE_PATH=/app/node_modules
      - LOGIN_URL=/ui/#/sign-in
      - DEFAULT_TARGET_SERVER=http://v-ui:8080
      - AUTH_API_SERVER=http://authserver:8080
      - AUTH_API_PREFIX=/api/auth/v1
      - USER_INTERFACE_PREFIX=/ui
      - USER_INTERFACE_SERVER=http://v-ui:8080
      - CAN_SCHEME=http
      - CAN_SERVER=authserver
      - CAN_PORT=8080
      - CAN_PATH=/api/can/v1
      - CAN_TOKEN=abcd1234
    depends_on:
      - cockroachdb
      - initdb
  authserver:
    build: ./auth-server
    command: nodemon app.js
    volumes:
      - ./auth-server:/app
      - ./common:/common
    working_dir: /app
    environment:
      - PORT=8080
      - COCKROACH_HOST=cockroachdb
      - COCKROACH_PORT=26257
      - COCKROACH_USER=tamer
      - COCKROACH_DATABASE=tamedb
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - APP_REDIRECT_URL=http://localhost:8080/ui
      - NODE_PATH=/app/node_modules
      - CAN_TOKEN=abcd1234
    depends_on:
      - cockroachdb
      - initdb
  user-interface:
    build: ./user-interface
    command: npm run dev
    volumes:
      - ./user-interface:/app
    working_dir: /app
    environment:
      - PORT=8080
      - API=/api
    depends_on:
      - authserver
      - proxy
  v-ui:
    build: ./v-ui
    command: npm run dev
    volumes:
      - ./v-ui:/app
    working_dir: /app
    environment:
      - PORT=8080
      - API=/api
    ports:
      - 8888:8080
    depends_on:
      - authserver
      - proxy
  cockroachdb:
    image: cockroachdb/cockroach:v1.1.5
    command: start --insecure
    volumes:
      - ./data/cockroachdb:/cockroach/cockroach-data
    ports:
      - 8001:8080
  initdb:
    image: cockroachdb/cockroach:v1.1.5
    command: sql --insecure -e 'CREATE DATABASE tamedb; GRANT ALL ON DATABASE tamedb TO tamer'
    environment:
      - COCKROACH_HOST=cockroachdb
      - COCKROACH_PORT=26257
      - COCKROACH_USER=root
      - COCKROACH_DATABASE=tamedb
    depends_on:
      - cockroachdb
  registry:
    build: ./registry
    command: nodemon app.js
    volumes:
      - ./registry:/app
      - ./common:/common
    working_dir: /app
    environment:
      - NODE_PATH=/app/node_modules
      - COCKROACH_HOST=cockroachdb
      - COCKROACH_PORT=26257
      - COCKROACH_USER=root
      - COCKROACH_DATABASE=tamedb
    depends_on:
      - authserver
      - proxy
      - cockroachdb
  # minio:
  #   image: minio/minio:latest
  #   command: server /export
  #   volumes:
  #     - ./data/minio:/export
  #   environment:
  #     - MINIO_ACCESS_KEY=testKey
  #     - MINIO_SECRET_KEY=testSecret123
  #   ports:
  #     - 9000:9000
  # kong:
  #   image: kong:latest
  #   ports:
  #     - 80:8000
  #     - 443:8443
  #     - 8002:8001
  #     - 8444:8444
  #   environment:
  #     - KONG_DATABASE=postgres
  #     - KONG_PG_HOST=cockroachdb
  #     - KONG_PG_USER=root
  #     - KONG_ADMIN_LISTEN=0.0.0.0:8001
  #     - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
  #   depends_on:
  #     - cockroachdb
  # kong-init:
  #   image: kong:latest
  #   command: kong migrations up
  #   environment:
  #     - KONG_DATABASE=postgres
  #     - KONG_PG_HOST=cockroachdb
  #   depends_on:
  #     - cockroachdb

