version: '3'
services:
  proxy:
    build: ./proxy
    command: nodemon app.js
    volumes:
      - ./proxy:/app
      - ./common:/common
    working_dir: /app
    ports:
      - 8080:8080
    environment:
      - NODE_PATH=/app/node_modules
      - LOGIN_URL=/ui/#/sign-in
      - DEFAULT_TARGET_SERVER=http://userinterface:8080
      - AUTH_API_SERVER=http://authserver:8080
      - AUTH_API_PREFIX=/api/auth/v1
      - USER_INTERFACE_PREFIX=/ui
      - USER_INTERFACE_SERVER=http://userinterface:8080
    depends_on:
      - cockroachdb
      - initdb
  authserver:
    build: ./auth-server
    command: nodemon app.js
    volumes:
      - ./auth-server:/app
      - ./common:/common
    working_dir: /app
    environment:
      - PORT=8080
      - COCKROACH_HOST=cockroachdb
      - COCKROACH_PORT=26257
      - COCKROACH_USER=tamer
      - COCKROACH_DATABASE=tamedb
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - APP_REDIRECT_URL=http://localhost:8080/ui
      - NODE_PATH=/app/node_modules
    depends_on:
      - cockroachdb
      - initdb
  userinterface:
    build: ./user-interface
    command: npm run dev
    volumes:
      - ./user-interface:/app
    working_dir: /app
    environment:
      - PORT=8080
      - API=/api
    depends_on:
      - authserver
      - proxy
  cockroachdb:
    image: cockroachdb/cockroach:v1.1.5
    command: start --insecure
    volumes:
      - ./data/cockroachdb:/cockroach/cockroach-data
    ports:
      - 8001:8080
  initdb:
    image: cockroachdb/cockroach:v1.1.5
    command: sql --insecure -e 'CREATE DATABASE tamedb; GRANT ALL ON DATABASE tamedb TO tamer'
    environment:
      - COCKROACH_HOST=cockroachdb
      - COCKROACH_PORT=26257
      - COCKROACH_USER=root
      - COCKROACH_DATABASE=tamedb
    depends_on:
      - cockroachdb

